export const CarOptions = {
    brandsWithModels: {
        Toyota: ['Corolla', 'Camry', 'RAV4', 'Yaris', 'Highlander'],
        Honda: ['Civic', 'Accord', 'CR-V', 'Fit', 'Pilot'],
        Ford: ['Focus', 'Fiesta', 'Mustang', 'Explorer', 'Escape'],
        BMW: ['3 Series', '5 Series', 'X5', 'X3', '7 Series'],
        Mercedes: ['C-Class', 'E-Class', 'S-Class', 'GLA', 'GLE'],
        Audi: ['A3', 'A4', 'A6', 'Q5', 'Q7'],
        Chevrolet: ['Malibu', 'Impala', 'Equinox', 'Tahoe', 'Silverado'],
        Nissan: ['Altima', 'Maxima', 'Rogue', 'Sentra', 'Murano'],
        Hyundai: ['Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Accent'],
        Kia: ['Soul', 'Sportage', 'Sorento', 'Optima', 'Rio'],
        Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y'],
        Volkswagen: ['Golf', 'Passat', 'Tiguan', 'Polo', 'Jetta'],
        Mazda: ['Mazda2', 'Mazda3', 'Mazda6', 'CX-5', 'MX-5'],
        Subaru: ['Impreza', 'Legacy', 'Outback', 'Forester', 'BRZ'],
        Porsche: ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
        Ferrari: ['488', 'Portofino', 'Roma', 'F8 Tributo', 'SF90'],
        Lamborghini: ['Huracán', 'Aventador', 'Urus', 'Gallardo', 'Murciélago'],
        Jaguar: ['XE', 'XF', 'XJ', 'F-Pace', 'E-Pace'],
        Volvo: ['S60', 'S90', 'XC40', 'XC60', 'XC90'],
        Mitsubishi: ['Mirage', 'Lancer', 'Outlander', 'Pajero', 'Eclipse Cross'],
        Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler'],
        Chrysler: ['300', 'Pacifica', 'Voyager', 'Aspen', 'Crossfire'],
        Peugeot: ['208', '308', '508', '2008', '3008'],
        Renault: ['Clio', 'Megane', 'Captur', 'Kadjar', 'Talisman'],
        Škoda: ['Fabia', 'Octavia', 'Superb', 'Karoq', 'Kodiaq'],
        Fiat: ['500', 'Panda', 'Tipo', 'Punto', 'Doblo'],
        Suzuki: ['Swift', 'Baleno', 'Vitara', 'S-Cross', 'Jimny'],
    },
    fuelType: ['petrol', 'diesel', 'electric', 'hybrid'],
    transmission: ['manual', 'automatic'],
}
